language: java
jdk:
- openjdk8
install: mvn install -DskipTests=true -Dgpg.skip=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn -Dgpg.skip=true package
after_success:
- bash <(curl -s https://codecov.io/bash)
before_deploy:
  - export RELEASE_PKG_FILE=$(ls target/*.jar)
  - echo "Deploy $RELEASE_PKG_FILE ..."
deploy:
  provider: releases
  api_key:
    secure: "r/7Pl0nxf8tzMgvd+eL6PknijFGmaN1dMBp5/f+fXvQMC74UZNFQFlhi5naacAYTDDKHNvwuY1w3jKTio+cc5C1sE5xw2QyV11Fz8u/Z4YYnjZUB5BZcazKSO+mJkth4CJwoxNjlZlB4+kRi8PIXrGCvCnoJMmd/uZhETlXMbU+lbM/uoApPWic1bmP8wY26xVSOlZlUg8XVOjeAq4GjhZ2oGv2FaQjZsG9Y9IE1xRwQcV7JGPO5P71Rue/HN2x85PIntdGcwr3BEEyk5e/dmoiu5IHDV2Lxz+DkDOO7Xan5dz6S3poNfNoNcf7P7eTVx4m6JvWyatUI2SalW8MDT6oj86DqomwM/AKhPZG5O5qLKX/qXzJVIHyABZUJ/J4KUuribdJdYchXDqPawyB01YTFz1m5SvM8+FRzax2V4/hwh2g60o+mXH6YcYZqLu0FCutDeDHq3FcVUmGKI2Ni+hFqvF6swV1ZnstlsvZGeHPsp2XsOuwboSOJYM2jI6q3Qm24w/jC2XWv+QDqmF6rEqNjdGIO5d9e5EFAaHn3UfVa0gW3YF0PyDHLa6X3x2vQMNNUGjZ8lnu9zEriCPIo4j546eO8BDMBH9iaa9CqiDTiKdavapES+PJ+Q9MH05H8xc+GMoGn+l0UXPV+PZ77hALF22S1GQ5I/zrBVxDn324="
  file_glob: true
  skip_cleanup: true
  file: "${RELEASE_PKG_FILE}"
  on:
    repo: ViiSE/papka
    tags: true
